config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    unlocks: 'accounts/unlocks'
  }

  resources :projects do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks do
    member do
      post :update_status
    end
  end

  root to: "projects#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_importmap_tags 'application' %>
  </head>  <!-- ... -->

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Taskapp</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <% unless account_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign up', new_account_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login', new_account_session_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_account_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'New Project', new_project_path, class: 'nav-link' %>
            </li>
            <% if cookies[:current_project_id].present? %>
              <li class="nav-item">
                <%= link_to 'New Task', new_task_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item">
              Logged in as: <%= current_account.email %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>